// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: godrive/v1/godrive.proto

package godrivev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{0}
}

///////////////////////////
// Auth domain messages  //
///////////////////////////
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // DB primary key
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                          // unique email
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // plaintext over TLS; stored hashed server-side
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{2}
}

func (x *Credentials) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // JWT string
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`       // token expiry in ISO time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{3}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

///////////////////////////
// Files domain messages //
///////////////////////////
type FileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`       // user ID that owns this file
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                             // filename as user sees it
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`                             // MIME type
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // size recorded on confirm
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // ISO timestamp
	VersionId     string                 `protobuf:"bytes,7,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`  // placeholder for S3 versioning later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileItem) Reset() {
	*x = FileItem{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileItem) ProtoMessage() {}

func (x *FileItem) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileItem.ProtoReflect.Descriptor instead.
func (*FileItem) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{4}
}

func (x *FileItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileItem) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *FileItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileItem) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *FileItem) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FileItem) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ListFilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileItem            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	NextPage      int32                  `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"` // 0 if none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{6}
}

func (x *ListFilesResponse) GetFiles() []*FileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetNextPage() int32 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

// Client asks storage for an upload URL; gateway composes this request.
type CreateUploadIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadIntentRequest) Reset() {
	*x = CreateUploadIntentRequest{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadIntentRequest) ProtoMessage() {}

func (x *CreateUploadIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadIntentRequest) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUploadIntentRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateUploadIntentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateUploadIntentRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *CreateUploadIntentRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type CreateUploadIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`                                                      // S3 object path (e.g., user/123/...)
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // any required headers for PUT
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadIntentResponse) Reset() {
	*x = CreateUploadIntentResponse{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadIntentResponse) ProtoMessage() {}

func (x *CreateUploadIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadIntentResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadIntentResponse) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUploadIntentResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateUploadIntentResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *CreateUploadIntentResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreateUploadIntentResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ConfirmUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // final S3 key the client PUT to
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmUploadRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ConfirmUploadRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ConfirmUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConfirmUploadRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ConfirmUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ConfirmUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileItem              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadResponse) Reset() {
	*x = ConfirmUploadResponse{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadResponse) ProtoMessage() {}

func (x *ConfirmUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUploadResponse) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmUploadResponse) GetFile() *FileItem {
	if x != nil {
		return x.File
	}
	return nil
}

type DownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FileId        int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadURLRequest) Reset() {
	*x = DownloadURLRequest{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadURLRequest) ProtoMessage() {}

func (x *DownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadURLRequest.ProtoReflect.Descriptor instead.
func (*DownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadURLRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *DownloadURLRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type DownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // pre-signed GET URL (or placeholder in first pass)
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadURLResponse) Reset() {
	*x = DownloadURLResponse{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadURLResponse) ProtoMessage() {}

func (x *DownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadURLResponse.ProtoReflect.Descriptor instead.
func (*DownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadURLResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *DownloadURLResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FileId        int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteFileRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *DeleteFileRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

/////////////////////////////
// Storage domain messages //
/////////////////////////////
type PresignUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"` // where the object will live
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignUploadRequest) Reset() {
	*x = PresignUploadRequest{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUploadRequest) ProtoMessage() {}

func (x *PresignUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUploadRequest.ProtoReflect.Descriptor instead.
func (*PresignUploadRequest) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{15}
}

func (x *PresignUploadRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PresignUploadRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *PresignUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type PresignUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                                                                   // PUT URL
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., Content-Type if required
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignUploadResponse) Reset() {
	*x = PresignUploadResponse{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUploadResponse) ProtoMessage() {}

func (x *PresignUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUploadResponse.ProtoReflect.Descriptor instead.
func (*PresignUploadResponse) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{16}
}

func (x *PresignUploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PresignUploadResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PresignUploadResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type PresignDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignDownloadRequest) Reset() {
	*x = PresignDownloadRequest{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignDownloadRequest) ProtoMessage() {}

func (x *PresignDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignDownloadRequest.ProtoReflect.Descriptor instead.
func (*PresignDownloadRequest) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{17}
}

func (x *PresignDownloadRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type PresignDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // GET URL
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignDownloadResponse) Reset() {
	*x = PresignDownloadResponse{}
	mi := &file_godrive_v1_godrive_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignDownloadResponse) ProtoMessage() {}

func (x *PresignDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_godrive_v1_godrive_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignDownloadResponse.ProtoReflect.Descriptor instead.
func (*PresignDownloadResponse) Descriptor() ([]byte, []int) {
	return file_godrive_v1_godrive_proto_rawDescGZIP(), []int{18}
}

func (x *PresignDownloadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PresignDownloadResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_godrive_v1_godrive_proto protoreflect.FileDescriptor

const file_godrive_v1_godrive_proto_rawDesc = "" +
	"\n" +
	"\x18godrive/v1/godrive.proto\x12\n" +
	"godrive.v1\"\a\n" +
	"\x05Empty\"K\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"?\n" +
	"\vCredentials\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"I\n" +
	"\x05Token\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"\xba\x01\n" +
	"\bFileItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"version_id\x18\a \x01(\tR\tversionId\"^\n" +
	"\x10ListFilesRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\\\n" +
	"\x11ListFilesResponse\x12*\n" +
	"\x05files\x18\x01 \x03(\v2\x14.godrive.v1.FileItemR\x05files\x12\x1b\n" +
	"\tnext_page\x18\x02 \x01(\x05R\bnextPage\"\x85\x01\n" +
	"\x19CreateUploadIntentRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\x84\x02\n" +
	"\x1aCreateUploadIntentResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12M\n" +
	"\aheaders\x18\x03 \x03(\v23.godrive.v1.CreateUploadIntentResponse.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x14ConfirmUploadRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\"A\n" +
	"\x15ConfirmUploadResponse\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.godrive.v1.FileItemR\x04file\"H\n" +
	"\x12DownloadURLRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\"W\n" +
	"\x13DownloadURLResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"G\n" +
	"\x11DeleteFileRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\"$\n" +
	"\x12DeleteFileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"h\n" +
	"\x14PresignUploadRequest\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"\xce\x01\n" +
	"\x15PresignUploadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12H\n" +
	"\aheaders\x18\x02 \x03(\v2..godrive.v1.PresignUploadResponse.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x16PresignDownloadRequest\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\"J\n" +
	"\x17PresignDownloadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt2\xa6\x01\n" +
	"\vAuthService\x123\n" +
	"\x06SignUp\x12\x17.godrive.v1.Credentials\x1a\x10.godrive.v1.User\x123\n" +
	"\x05Login\x12\x17.godrive.v1.Credentials\x1a\x11.godrive.v1.Token\x12-\n" +
	"\x06Verify\x12\x11.godrive.v1.Token\x1a\x10.godrive.v1.User2\xc5\x02\n" +
	"\fFilesService\x12C\n" +
	"\x04List\x12\x1c.godrive.v1.ListFilesRequest\x1a\x1d.godrive.v1.ListFilesResponse\x12T\n" +
	"\rConfirmUpload\x12 .godrive.v1.ConfirmUploadRequest\x1a!.godrive.v1.ConfirmUploadResponse\x12G\n" +
	"\x06Delete\x12\x1d.godrive.v1.DeleteFileRequest\x1a\x1e.godrive.v1.DeleteFileResponse\x12Q\n" +
	"\x0eGetDownloadURL\x12\x1e.godrive.v1.DownloadURLRequest\x1a\x1f.godrive.v1.DownloadURLResponse2\xc2\x01\n" +
	"\x0eStorageService\x12T\n" +
	"\rPresignUpload\x12 .godrive.v1.PresignUploadRequest\x1a!.godrive.v1.PresignUploadResponse\x12Z\n" +
	"\x0fPresignDownload\x12\".godrive.v1.PresignDownloadRequest\x1a#.godrive.v1.PresignDownloadResponseB$Z\"godrive/proto/godrive/v1;godrivev1b\x06proto3"

var (
	file_godrive_v1_godrive_proto_rawDescOnce sync.Once
	file_godrive_v1_godrive_proto_rawDescData []byte
)

func file_godrive_v1_godrive_proto_rawDescGZIP() []byte {
	file_godrive_v1_godrive_proto_rawDescOnce.Do(func() {
		file_godrive_v1_godrive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_godrive_v1_godrive_proto_rawDesc), len(file_godrive_v1_godrive_proto_rawDesc)))
	})
	return file_godrive_v1_godrive_proto_rawDescData
}

var file_godrive_v1_godrive_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_godrive_v1_godrive_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: godrive.v1.Empty
	(*User)(nil),                       // 1: godrive.v1.User
	(*Credentials)(nil),                // 2: godrive.v1.Credentials
	(*Token)(nil),                      // 3: godrive.v1.Token
	(*FileItem)(nil),                   // 4: godrive.v1.FileItem
	(*ListFilesRequest)(nil),           // 5: godrive.v1.ListFilesRequest
	(*ListFilesResponse)(nil),          // 6: godrive.v1.ListFilesResponse
	(*CreateUploadIntentRequest)(nil),  // 7: godrive.v1.CreateUploadIntentRequest
	(*CreateUploadIntentResponse)(nil), // 8: godrive.v1.CreateUploadIntentResponse
	(*ConfirmUploadRequest)(nil),       // 9: godrive.v1.ConfirmUploadRequest
	(*ConfirmUploadResponse)(nil),      // 10: godrive.v1.ConfirmUploadResponse
	(*DownloadURLRequest)(nil),         // 11: godrive.v1.DownloadURLRequest
	(*DownloadURLResponse)(nil),        // 12: godrive.v1.DownloadURLResponse
	(*DeleteFileRequest)(nil),          // 13: godrive.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),         // 14: godrive.v1.DeleteFileResponse
	(*PresignUploadRequest)(nil),       // 15: godrive.v1.PresignUploadRequest
	(*PresignUploadResponse)(nil),      // 16: godrive.v1.PresignUploadResponse
	(*PresignDownloadRequest)(nil),     // 17: godrive.v1.PresignDownloadRequest
	(*PresignDownloadResponse)(nil),    // 18: godrive.v1.PresignDownloadResponse
	nil,                                // 19: godrive.v1.CreateUploadIntentResponse.HeadersEntry
	nil,                                // 20: godrive.v1.PresignUploadResponse.HeadersEntry
}
var file_godrive_v1_godrive_proto_depIdxs = []int32{
	4,  // 0: godrive.v1.ListFilesResponse.files:type_name -> godrive.v1.FileItem
	19, // 1: godrive.v1.CreateUploadIntentResponse.headers:type_name -> godrive.v1.CreateUploadIntentResponse.HeadersEntry
	4,  // 2: godrive.v1.ConfirmUploadResponse.file:type_name -> godrive.v1.FileItem
	20, // 3: godrive.v1.PresignUploadResponse.headers:type_name -> godrive.v1.PresignUploadResponse.HeadersEntry
	2,  // 4: godrive.v1.AuthService.SignUp:input_type -> godrive.v1.Credentials
	2,  // 5: godrive.v1.AuthService.Login:input_type -> godrive.v1.Credentials
	3,  // 6: godrive.v1.AuthService.Verify:input_type -> godrive.v1.Token
	5,  // 7: godrive.v1.FilesService.List:input_type -> godrive.v1.ListFilesRequest
	9,  // 8: godrive.v1.FilesService.ConfirmUpload:input_type -> godrive.v1.ConfirmUploadRequest
	13, // 9: godrive.v1.FilesService.Delete:input_type -> godrive.v1.DeleteFileRequest
	11, // 10: godrive.v1.FilesService.GetDownloadURL:input_type -> godrive.v1.DownloadURLRequest
	15, // 11: godrive.v1.StorageService.PresignUpload:input_type -> godrive.v1.PresignUploadRequest
	17, // 12: godrive.v1.StorageService.PresignDownload:input_type -> godrive.v1.PresignDownloadRequest
	1,  // 13: godrive.v1.AuthService.SignUp:output_type -> godrive.v1.User
	3,  // 14: godrive.v1.AuthService.Login:output_type -> godrive.v1.Token
	1,  // 15: godrive.v1.AuthService.Verify:output_type -> godrive.v1.User
	6,  // 16: godrive.v1.FilesService.List:output_type -> godrive.v1.ListFilesResponse
	10, // 17: godrive.v1.FilesService.ConfirmUpload:output_type -> godrive.v1.ConfirmUploadResponse
	14, // 18: godrive.v1.FilesService.Delete:output_type -> godrive.v1.DeleteFileResponse
	12, // 19: godrive.v1.FilesService.GetDownloadURL:output_type -> godrive.v1.DownloadURLResponse
	16, // 20: godrive.v1.StorageService.PresignUpload:output_type -> godrive.v1.PresignUploadResponse
	18, // 21: godrive.v1.StorageService.PresignDownload:output_type -> godrive.v1.PresignDownloadResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_godrive_v1_godrive_proto_init() }
func file_godrive_v1_godrive_proto_init() {
	if File_godrive_v1_godrive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_godrive_v1_godrive_proto_rawDesc), len(file_godrive_v1_godrive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_godrive_v1_godrive_proto_goTypes,
		DependencyIndexes: file_godrive_v1_godrive_proto_depIdxs,
		MessageInfos:      file_godrive_v1_godrive_proto_msgTypes,
	}.Build()
	File_godrive_v1_godrive_proto = out.File
	file_godrive_v1_godrive_proto_goTypes = nil
	file_godrive_v1_godrive_proto_depIdxs = nil
}
